Content-Type: multipart/mixed; boundary="------------mrM5nkpX3g7Cpl1orQFwlZJZ"
Message-ID: <77ce1dc5-2630-4a76-b527-64ca3fd8b2f6@fitus.edu.vn>
Date: Sun, 19 Nov 2023 05:00:09 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: vi-x-KieuCu.[Chuan]
To: example@example.com
From: =?UTF-8?Q?Xu=C3=A2n_Thanh?= <lxthanh22clc@fitus.edu.vn>
Subject: TEST THUNDERBIRD

This is a multi-part message in MIME format.
--------------mrM5nkpX3g7Cpl1orQFwlZJZ
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

ALO

--------------mrM5nkpX3g7Cpl1orQFwlZJZ
Content-Type: text/plain; charset=UTF-8; name="ATTACHMENT.txt"
Content-Disposition: attachment; filename="ATTACHMENT.txt"
Content-Transfer-Encoding: base64

YWxvYWxv
--------------mrM5nkpX3g7Cpl1orQFwlZJZ
Content-Type: text/plain; charset=UTF-8; name="ATTACHMENT2.txt"
Content-Disposition: attachment; filename="ATTACHMENT2.txt"
Content-Transfer-Encoding: base64

eHhjdnhjdnh2Yw==

--------------mrM5nkpX3g7Cpl1orQFwlZJZ--
