Content-Type: multipart/mixed; boundary="===============8188923111465385999=="
MIME-Version: 1.0
Message-ID: Message ID: fb6fdaca-aef0-492f-8da1-64da037913c3@example.com
Date: Date: Sun, 19 Nov 2023 04:21:48 +0700
To: example@example.com
From: Mang may tinh <example@example.com>
Subject: TEST 04

--===============8188923111465385999==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

04
--===============8188923111465385999==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/plain
Content-Disposition: attachment;
 filename="C:/Users/lxtha/Desktop/ATTACHMENT.txt"

YWxvYWxv

--===============8188923111465385999==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/plain
Content-Disposition: attachment;
 filename="C:/Users/lxtha/Desktop/ATTACHMENT2.txt"

eHhjdnhjdnh2Yw==

--===============8188923111465385999==--

