Content-Type: multipart/mixed; boundary="===============3850212839994980093=="
MIME-Version: 1.0
Message-ID: 99c6ca6f-1685-4643-8128-72e01048a0cd@example.com
Date: Fri, 24 Nov 2023 23:15:00 +0700
To: example@example.com
Cc: 
From: Mang may tinh <example@example.com>
Subject: 123123

--===============3850212839994980093==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

123123
--===============3850212839994980093==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/plain
Content-Disposition: attachment;
 filename*=utf-8''C%3A%5CUsers%5CAdmins%5CDesktop%5CM%E1%BA%A1ng%20m%C3%A1y%20t%C3%ADnh%5CTai_lieu_Socket%5Csample_code%5Cinput.txt

QVM=

--===============3850212839994980093==--

