Content-Type: multipart/mixed; boundary="===============2499642944392005993=="
MIME-Version: 1.0
Message-ID: 9b334b04-db6c-43e2-951c-d0e94b566d82@example.com
Date: Sun, 26 Nov 2023 12:28:12 +0700
To: example@example.com
Cc: 
From: Mang may tinh <example@example.com>
Subject: TEST tACH

--===============2499642944392005993==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

alo
--===============2499642944392005993==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/plain
Content-Disposition: attachment; filename="input.txt"

YTthYWFzZGFkYXNkYWRhc2RhZGFzZGFka3ZqZnNkbGt2anNkbGZ2a2phd2Vpb3JqYWVmamF3b2ll
dmphdm5ka25jYXNsZGtmanNhbGZr

--===============2499642944392005993==--

