Content-Type: multipart/mixed; boundary="===============1679886980923253413=="
MIME-Version: 1.0
Message-ID: d48cc51e-11a2-4f4b-af8c-bb8d385545a3@example.com
Date: Sat, 25 Nov 2023 00:43:47 +0700
To: example@example.com
Cc: 
From: Mang may tinh <example@example.com>
Subject: TET 

--===============1679886980923253413==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

TESt
--===============1679886980923253413==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/plain
Content-Disposition: attachment; filename="input.txt"

YTthYWFzZGFkYXNkYWRhc2RhZGFzZGFka3ZqZnNkbGt2anNkbGZ2a2phd2Vpb3JqYWVmamF3b2ll
dmphdm5ka25jYXNsZGtmanNhbGZr

--===============1679886980923253413==--

