Content-Type: multipart/mixed; boundary="===============7061727832778810389=="
MIME-Version: 1.0
Message-ID: 4bfe2a56-fd82-4cbe-b83c-ffc9fbf83c37@example.com
Date: Sat, 25 Nov 2023 00:31:21 +0700
To: example@example.com
Cc: 
From: Mang may tinh <example@example.com>
Subject: THU 

--===============7061727832778810389==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

THU
--===============7061727832778810389==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/plain
Content-Disposition: attachment;
 filename="C:\\Users\\Admins\\Desktop\\input.txt"

YTthYWFzZGFkYXNkYWRhc2RhZGFzZGFka3ZqZnNkbGt2anNkbGZ2a2phd2Vpb3JqYWVmamF3b2ll
dmphdm5ka25jYXNsZGtmanNhbGZr

--===============7061727832778810389==--

