Content-Type: multipart/mixed; boundary="===============0894373452566582973=="
MIME-Version: 1.0
Message-ID: 57d62ff2-c06d-4a58-b67e-1b79d8e3d0eb@example.com
Date: Sat, 25 Nov 2023 01:27:27 +0700
To: example@example.com
Cc: 
From: Mang may tinh <example@example.com>
Subject: 1

--===============0894373452566582973==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

1
--===============0894373452566582973==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/plain
Content-Disposition: attachment; filename="input.txt"

YTthYWFzZGFkYXNkYWRhc2RhZGFzZGFka3ZqZnNkbGt2anNkbGZ2a2phd2Vpb3JqYWVmamF3b2ll
dmphdm5ka25jYXNsZGtmanNhbGZr

--===============0894373452566582973==--

