Content-Type: multipart/mixed; boundary="===============2249626590668286733=="
MIME-Version: 1.0
Message-ID: 66cc731b-7e4f-4948-be79-472ae53ae800@example.com
Date: Sat, 25 Nov 2023 16:53:33 +0700
To: example@example.com
Cc: giathiec
From: Mang may tinh <example@example.com>
Subject: 

--===============2249626590668286733==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

ALO
--===============2249626590668286733==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/plain
Content-Disposition: attachment; filename="ATTACHMENT.txt"

YWxvYWxv

--===============2249626590668286733==--

