Content-Type: multipart/mixed; boundary="===============5129349785019849093=="
MIME-Version: 1.0
Message-ID: 40ee3461-6e62-404b-a613-87e8802909eb@example.com
Date: Sun, 19 Nov 2023 04:25:05 +0700
To: example@example.com
From: Mang may tinh <example@example.com>
Subject: TEST 05

--===============5129349785019849093==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

05
--===============5129349785019849093==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/plain
Content-Disposition: attachment;
 filename="C:/Users/lxtha/Desktop/ATTACHMENT.txt"

YWxvYWxv

--===============5129349785019849093==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/plain
Content-Disposition: attachment;
 filename="C:/Users/lxtha/Desktop/ATTACHMENT2.txt"

eHhjdnhjdnh2Yw==

--===============5129349785019849093==--

