Content-Type: multipart/mixed; boundary="===============8562804551210030770=="
MIME-Version: 1.0
Message-ID: 75ae7144-840a-4969-8243-895ece96a8b5@example.com
Date: Sun, 19 Nov 2023 05:32:41 +0700
To: example@example.com
From: Mang may tinh <example@example.com>
Subject: TEST 3 FILES

--===============8562804551210030770==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit


--===============8562804551210030770==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/plain
Content-Disposition: attachment;
 filename="C:/Users/lxtha/Desktop/ATTACHMENT.txt"

YWxvYWxv

--===============8562804551210030770==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/plain
Content-Disposition: attachment;
 filename="C:/Users/lxtha/Desktop/ATTACHMENT.txt"

YWxvYWxv

--===============8562804551210030770==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/plain
Content-Disposition: attachment;
 filename="C:/Users/lxtha/Desktop/ATTACHMENT.txt"

YWxvYWxv

--===============8562804551210030770==--

