Content-Type: multipart/mixed; boundary="===============5838868307543207573=="
MIME-Version: 1.0
Message-ID: 143831df-5a12-4614-b7d3-ac8f8c28ee25@example.com
Date: Mon, 20 Nov 2023 13:58:37 +0700
To: example@example.com
From: Mang may tinh <example@example.com>
Subject: TEST

--===============5838868307543207573==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

test
--===============5838868307543207573==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/plain
Content-Disposition: attachment; filename="input.txt"

YTthYWFzZGFkYXNkYWRhc2RhZGFzZGFka3ZqZnNkbGt2anNkbGZ2a2phd2Vpb3JqYWVmamF3b2ll
dmphdm5ka25jYXNsZGtmanNhbGZr

--===============5838868307543207573==--

