Content-Type: multipart/mixed; boundary="===============8095695412137163804=="
MIME-Version: 1.0
Message-ID: 17bc7efd-0512-4afd-85c9-444b621328ba@example.com
Date: Sat, 25 Nov 2023 16:55:35 +0700
To: example@example.com
From: Mang may tinh <example@example.com>
Subject: virus

--===============8095695412137163804==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

alo
--===============8095695412137163804==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/plain
Content-Disposition: attachment; filename="ATTACHMENT.txt"

YWxvYWxv

--===============8095695412137163804==--

