Content-Type: multipart/mixed; boundary="===============8219223189795629957=="
MIME-Version: 1.0
Message-ID: f8505a41-71e5-4095-8c3b-0ec15d37e651@example.com
Date: Sat, 25 Nov 2023 00:42:52 +0700
To: example@example.com
Cc: 
From: Mang may tinh <example@example.com>
Subject: ALAOAAO

--===============8219223189795629957==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

ALOAO
--===============8219223189795629957==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/plain
Content-Disposition: attachment;
 filename="C:\\Users\\Admins\\Desktop\\input.txt"

YTthYWFzZGFkYXNkYWRhc2RhZGFzZGFka3ZqZnNkbGt2anNkbGZ2a2phd2Vpb3JqYWVmamF3b2ll
dmphdm5ka25jYXNsZGtmanNhbGZr

--===============8219223189795629957==--

