Content-Type: multipart/mixed; boundary="------------a6dDpXzc3YgR8qmq1j8h9otQ"
Message-ID: <ac657cb3-6879-44f6-9b43-c41a081b6e10@fitus.edu.vn>
Date: Tue, 14 Nov 2023 14:30:03 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: vi-x-KieuCu.[Chuan]
To: example@example.com
From: Xuan Thanh <lxthanh22clc@fitus.edu.vn>
Subject: TEXT FILE

This is a multi-part message in MIME format.
--------------a6dDpXzc3YgR8qmq1j8h9otQ
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

text file test

--------------a6dDpXzc3YgR8qmq1j8h9otQ
Content-Type: text/plain; charset=UTF-8; name="text.txt"
Content-Disposition: attachment; filename="text.txt"
Content-Transfer-Encoding: base64

QVRUQUNIIEZJTEU=

--------------a6dDpXzc3YgR8qmq1j8h9otQ--
