Content-Type: multipart/mixed; boundary="===============8329052328718130254=="
MIME-Version: 1.0
Message-ID: f35b49be-c3cd-4617-8331-e0ae34548921@example.com
Date: Sat, 25 Nov 2023 01:41:16 +0700
To: example@example.com
Cc: thiec,thu
From: Mang may tinh <example@example.com>
Subject: TEST FINAL

--===============8329052328718130254==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

alo
--===============8329052328718130254==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/plain
Content-Disposition: attachment; filename="input.txt"

YTthYWFzZGFkYXNkYWRhc2RhZGFzZGFka3ZqZnNkbGt2anNkbGZ2a2phd2Vpb3JqYWVmamF3b2ll
dmphdm5ka25jYXNsZGtmanNhbGZr

--===============8329052328718130254==--

