Message-ID: <47bb6e8e-30d1-4805-8de6-b1ce42afeb8c@fitus.edu.vn>
Date: Sun, 12 Nov 2023 10:04:36 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: vi-x-KieuCu.[Chuan]
To: lxthanh22clc@fitus.edu.vn
From: Xuan Thanh <lxthanh22clc@fitus.edu.vn>
Subject: TEST 01 12/11/2023
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

Hi Thanh,

test

Thank you

