Content-Type: multipart/mixed; boundary="------------l3sSzUISv6vLIGWITCwGi7RG"
Message-ID: <b9cc534b-186a-4a93-bc25-bc5a835f4ec8@fitus.edu.vn>
Date: Tue, 14 Nov 2023 14:50:20 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: vi-x-KieuCu.[Chuan]
To: lxthanh22clc@fitus.edu.vn
From: Xuan Thanh <lxthanh22clc@fitus.edu.vn>
Subject: FILE

This is a multi-part message in MIME format.
--------------l3sSzUISv6vLIGWITCwGi7RG
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

file

--------------l3sSzUISv6vLIGWITCwGi7RG
Content-Type: text/plain; charset=UTF-8; name="text.txt"
Content-Disposition: attachment; filename="text.txt"
Content-Transfer-Encoding: base64

QVRUQUNIIEZJTEU=

--------------l3sSzUISv6vLIGWITCwGi7RG--
