Content-Type: multipart/mixed; boundary="===============0698889305078834736=="
MIME-Version: 1.0
Message-ID: 25736cc0-ea4d-44ae-94d4-9e22e6519fb2@example.com
Date: Sat, 25 Nov 2023 01:37:07 +0700
To: example@example.com
Cc: giathiec,thu
From: Mang may tinh <example@example.com>
Subject: ALO TEST

--===============0698889305078834736==
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

TEST FINAL
--===============0698889305078834736==
Content-Transfer-Encoding: base64
MIME-Version: 1.0
Content-Type: text/plain
Content-Disposition: attachment; filename="input.txt"

YTthYWFzZGFkYXNkYWRhc2RhZGFzZGFka3ZqZnNkbGt2anNkbGZ2a2phd2Vpb3JqYWVmamF3b2ll
dmphdm5ka25jYXNsZGtmanNhbGZr

--===============0698889305078834736==--

